package binding

import (
	"github.com/wenlng/gonacli/config"
	"github.com/wenlng/gonacli/tools"
)

func GenPlatformHelper(filename string, cfgs config.Config) bool {
	code := `// Auto-generated by gonacli
'use strict';

function platformIdentifier() {
  const platform = process.platform;
  const arch = process.arch;
  const abi = process.versions && process.versions.modules ? process.versions.modules : 'unknown';
  return platform + '-' + arch + '-node-' + abi;
}

module.exports = {
  platformIdentifier,
};
`

	outputDir := tools.FormatDirPath(cfgs.OutPut)
	if err := tools.WriteFile(code, outputDir, filename); err != nil {
		return false
	}
	return true
}
